create table venues (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    address varchar(255) not null,
    capacity integer not null
);

create table events (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    date date not null,
    description varchar(255) not null
);
