alter table venues add column city varchar(255);
update venues set city = 'Unknown' where city is null;
alter table venues alter column city set not null;

create table categories (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    description varchar(255) not null
);

alter table events add column active boolean default true;
update events set active = true where active is null;
alter table events alter column active set not null;

alter table events add column venue_id bigint;
alter table events alter column venue_id set not null;

create table events_categories (
    event_id bigint not null,
    category_id bigint not null,
    primary key (event_id, category_id),
    constraint fk_events_categories_event foreign key (event_id) references events(id),
    constraint fk_events_categories_category foreign key (category_id) references categories(id)
);

alter table events add constraint fk_events_venue foreign key (venue_id) references venues(id);
